### PR TITLE
fix: change isPtr to true on listElemCode

### LINKED ISSUE #370: Defferent behavior from "encoding/json" for MarshalJSON
```go
package main

import (
	"database/sql"
	"encoding/json"
	"fmt"
	goccyjson "github.com/goccy/go-json"
)

func main() {
	v := []struct{
		NS NullString
	}{
		{
			NS: NullString{String:"test", Valid: true},
		},
	}

	got, _ := json.Marshal(v)
	fmt.Println(string(got)) // output: [{"NS":"test"}]

	got, _ = goccyjson.Marshal(v)
	fmt.Println(string(got)) // output: [{"NS":{"String":"test","Valid":true}}]
}

type NullString sql.NullString

func (s *NullString) MarshalJSON() ([]byte, error) {
	if !s.Valid {
		return json.Marshal(nil)
	}
	return json.Marshal(s.String)
}
```

When I change `(s *NullString)` to `(s NullString)`, it's fine. (and maybe I should do so.)
So, it is not a critical issue, but I would prefer that compatibility be supported.

### PR DESCRIPTION
**Pull request by orisano**
fix #370

### CODE REVIEW

File: internal/encoder/compiler.go [hunk 1]
```diff
@@ -487,7 +487,7 @@ func (c *Compiler) listElemCode(typ *runtime.Type) (Code, error) {
 	case typ.Kind() == reflect.Map:
 		return c.ptrCode(runtime.PtrTo(typ))
 	default:
-		code, err := c.typeToCodeWithPtr(typ, false)
+		code, err := c.typeToCodeWithPtr(typ, true)
```
Comment (goccy) [inline internal/encoder/compiler.go:490]: Hmm..., I feel that the fix to set `isPtr` to `true` is not correct to fix this issue ( 
since elem is not ptr type )

Comment (orisano) [reply internal/encoder/compiler.go:491]: I added comment!

**Comment by goccy** [comment]
Thanks !
