### PR TITLE
Fix decoding of slice with type implemented UnmarshalJSON

### LINKED ISSUE #195: Multiple "Unmarshal" calls on the same data slice lead to corrupted data that cannot be unmarshaled
We (@symflower) are currently in the process of migrating to a faster JSON package than "encoding/json" and this project seems to be a good replacement. However, before we can benchmark any further we need to get rid of (hopefully only) this bug.

This reproducer works with "encoding/json" but not with "github.com/goccy/go-json". I tried to minimize the problem down to how we handle dynamic types with JSON. We basically have multiple "Unmarshal" calls that look at the types and then execute the right unmarshal functionality with the given type. Minimized only the calls to "UNmarshal" truly matter.

```
package main

import (
	"fmt"

	gojson "github.com/goccy/go-json"
)

func main() {
	data := []byte(`[
		{
		  "Body": {
			"List": [
			  {
				"nodeType": "Call"
			  },
			  {
				"nodeType": "Call"
			  }
			],
			"nodeKind": "Block",
			"nodeType": "Statement"
		  },
		  "nodeType": "Function"
		},
		{
		  "Body": {
			"List": [],
			"nodeKind": "Block",
			"nodeType": "Statement"
		  },
		  "nodeType": "Function"
		}
	  ]
	`)

	if !gojson.Valid(data) {
		panic("stop")
	}

	var a []gojson.RawMessage
	if err := gojson.Unmarshal(data, &a); err != nil {
		panic(err)
	}

	fmt.Println("Original:")
	for i, data := range a {
		fmt.Printf("%d: %s\n", i, data)
	}

	fmt.Println("when iterated while unmarshaling:")
	for i, data := range a {
		fmt.Printf("%d: %s\n", i, data)

		var b map[string]gojson.RawMessage
		if err := gojson.Unmarshal(data, &b); err != nil {
			panic(err)
		}

		var c map[string]gojson.RawMessage
		if err := gojson.Unmarshal(b["Body"], &c); err != nil {
			panic(err)
		}

		var d []gojson.RawMessage
		if err := gojson.Unmarshal(c["List"], &d); err != nil {
			panic(err)
		}
	}
}

```

Produces:

```
Original:
0: {
                  "Body": {
                        "List": [
                          {
                                "nodeType": "Call"
                          },
                          {
                                "nodeType": "Call"
                          }
                        ],
                        "nodeKind": "Block",
                        "nodeType": "Statement"
                  },
                  "nodeType": "Function"
                }
1: {
                  "Body": {
                        "List": [],
                        "nodeKind": "Block",
                        "nodeType": "Statement"
                  },
                  "nodeType": "Function"
                }
when iterated while unmarshaling:
0: {
                  "Body": {
                        "List": [
                          {
                                "nodeType": "Call"
                          },
                          {
                                "nodeType": "Call"
                          }
                        ],
                        "nodeKind": "Block",
                        "nodeType": "Statement"
                  },
                  "nodeType": "Function"
                }
1: {
                                "nodeType": "Call"
                          }                     "nodeKind": "Block",
                        "nodeType": "Statement"
                  },
                  "nodeType": "Function"
                }
panic: invalid character '"' after top-level value

goroutine 1 [running]:
main.main()
        /home/zimmski/symflower/tt.go:59 +0x6c5
exit status 2
```

### PR DESCRIPTION
**Pull request by goccy**
fix #195 

In decoding `UnmarshalJSON`, it is assumed that the passed pointer is used as it is as a receiver. If a type that implements UnmarshalJSON is specified as an element of slice, this should be taken into consideration so that the pointer of the reused slice element is not passed as it is.

### CODE REVIEW

File: decode_slice.go [hunk 1]
```diff
@@ -119,6 +121,12 @@ func (d *sliceDecoder) decodeStream(s *stream, depth int64, p unsafe.Pointer) er
 				ep := unsafe.Pointer(uintptr(data) + uintptr(idx)*d.size)
 				if d.isElemPointerType {
 					*(*unsafe.Pointer)(ep) = nil // initialize elem pointer
+				} else if d.isElemSliceType {
+					*(*sliceHeader)(ep) = sliceHeader{
```
Comment (IncSW) [inline decode_slice.go:125]: I'm think it should be reuse original data and cap like a std json.

**Review by IncSW — CHANGES_REQUESTED** [review]
```
func TestJSONSlice(t *testing.T) {
	slice := []int{}
	err := json.Unmarshal([]byte(`[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`), &slice)
	if err != nil {
		t.Fatal(err)
	}
	t.Log(len(slice), cap(slice)) // 10 13

	err = json.Unmarshal([]byte(`[1]`), &slice)
	if err != nil {
		t.Fatal(err)
	}
	t.Log(len(slice), cap(slice)) // 1 13
}
```

**Comment by goccy** [comment]
@zimmski Thank you, I wait for your report

**Comment by zimmski** [comment]
I think it has something to do with data being marked as invalid... when i add a "Valid" call to our code, i see that go-json marks the JSON raw data as invalid.

Here is an ugly reproducer... sorry i cannot post the original content.


```
package main

import (
	"encoding/json"
	"fmt"
	"os"

	gojson "github.com/goccy/go-json"
)

func main() {
	original := []byte(`{"ABCDEFGHIJKL":[{"MNOPQRSTUVWX":[{"YABC":{"DEFG":[{"HIJKLMNO":{"PQRS":"TUVWXYABCDEFGHIJKLMNOPQRSTUVWXYABCDEFGHIJKLMNOPQRSTUVWXYABCDE","FGHIJKLM":"NOPQRSTUVW"},"XYABCDEFGH":[{"IJKLMNOP":"!=","Q":{"RSTU":"V","WXYABCDE":"FGHIJKLMNO"},"P":{"QRSTUVWX":"YAB"},"CDEFGHIJ":"KLMNOP","QRSTUVWX":"YABCDEFGHI"}],"JKLMNOPQRSTUVW":null,"XYABCDEF":"GHIJ"},{"KLMNOPQR":{"STUVWXY":{"ABCDEFGH":"IJKLMN_OPQ_RST","U":{"VWXY":"A","BCDEFGHI":"JKLMNOPQRS"},"TUVWXYAB":"CDEFG","HIJKLMNO":"PQRSTUVWXY"},"ABCDEFGH":"IJKLMNOP!Q41R8ST98U00V204W9800998XYA8427B","CDEFGHIJ":"KLMNOP","QRSTUVWX":"YABCDEFGHI"},"JKLMNOPQRS":null,"TUVWXYABCDEFGH":null,"IJKLMNOP":"QRST"}],"UVWXYABC":"DEFGH","IJKLMNOP":"QRSTUVWXY"},"ABCDEFGH":9,"IJKL":"MNOPQRST/UVWXYABCDE//FGHIJKLMNOPQRST!4UV2WXYABC7826D7659EF223GH40I91J","KLMNOPQRST":[{"UVWXYABCDEFG":null,"HIJKLMNO":0,"PQRS":"T","UVWX":{"YABC":{"DEFG":"HIJK/LMNO/PQRSTU","VWXYABCD":"EFGHIJKLM","NOPQRSTU":"VWXY"},"ABCDEFGH":"IJKLMNO","PQRSTUVW":"XYAB"},"CDEFGHIJ":"KLMNOPQR"}],"STUVWXYA":null,"BCDEFGH":null,"IJKLMN":null,"OPQRSTUVWXYABC":null,"DEFGHIJK":"LMNOPQRS"},{"TUVW":{"XYAB":[{"CDEFGHIJ":{"KLMN":"OPQRSTUV/WXYABCDEFG//HIJKLMNOPQRSTUV!4WX2YABCDE7826F7659GH223IJ40K91L","MNOPQRST":"UVWXYABCDE"},"FGHIJKLMNO":[{"PQRS":"T","UVWXYABC":"DEFGHIJKLM"}],"NOPQRSTUVWXYAB":null,"CDEFGHIJ":"KLMN"}],"OPQRSTUV":"WXYAB","CDEFGHIJ":"KLMNOPQRS"},"TUVWXYAB":9,"CDEF":"GHIJKLMN/OPQRSTUVWX//YABCDEFGHIJKLM!4NO2PQRSTU7826V7659WX223YA40B91C","DEFGHIJKLM":[{"NOPQRSTUVWXY":null,"ABCDEFGH":0,"IJKL":"M","NOPQ":{"RSTU":{"VWXY":"ABCD/EFGH/IJKLMN","OPQRSTUV":"WXYABCDEF","GHIJKLMN":"OPQR"},"STUVWXYA":"BCDEFGH","IJKLMNOP":"QRST"},"UVWXYABC":"DEFGHIJK"}],"LMNOPQRS":null,"TUVWXYA":null,"BCDEFG":null,"HIJKLMNOPQRSTU":null,"VWXYABCD":"EFGHIJKL"},{"MNOP":{"QRST":[{"UVWXYABC":0,"DEFG":["HIJK"],"LMNO":[{"PQRS":{"TUVW":"XYABCDEF/GHIJKLMNOP","QRSTUVWX":"YABCDEFGH","IJKLMNOP":"QRST"},"UVWXYABC":"DEFGHIJ","KLMNOPQR":"STUV"}],"WXYAB":[{"CDEF":{"GHIJ":{"KLMN":"OPQRSTUV/WXYABCDEFG","HIJKLMNO":"PQRSTUVWX","YABCDEFG":"HIJK"},"LMNOPQRS":"TUVWXYA","BCDEFGHI":"JKLM"},"NOPQRSTU":"VWX"}],"YABCDEFG":"HIJKLMNOPQR","STUVWXYA":"BCDEFGHIJ"},{"KLMNOPQR":"=","S":{"TUVWXYA":{"BCDE":"FGHI","JKLMNOPQ":"RSTUVWXYAB"},"CDEFGHIJ":"@KLMN/OPQR/STUVWX","YABCDEFG":"HIJKLM","NOPQRSTU":"VWXYABCDEF"},"G":{"HIJKLMNO":{"PQRS":"TUVW/XYAB/CDEFGH//IJKLMN!O41P8QR98S00T204U9800998VWX8427Y","ABCDEFGH":"IJKLMNOPQR"},"STUVWXYABC":null,"DEFGHIJKLMNOPQ":null,"RSTUVWXY":"ABCD"},"EFGHIJKL":"MNOPQR","STUVWXYA":"BCDEFGHIJK"},{"LMNOPQR":[{"STUV":"WXYA","BCDEFGHI":"JKLMNOPQRS"}],"TUVWXYAB":"CDEFGH","IJKLMNOP":"QRSTUVWXY"}],"ABCDEFGH":"IJKLM","NOPQRSTU":"VWXYABCDE"},"FGHIJKLM":37,"NOPQ":"RSTUVWXY/ABCDEFGHIJ//KLMNOPQRST!U41V8WX98Y00A204B9800998CDE8427F","GHIJKLMNOP":null,"QRSTUVWX":null,"YABCDEF":[{"GHIJKLMNOPQR":null,"STUVWXYA":0,"BCDE":"","FGHI":{"JKLM":{"NOPQ":"RSTUVWXY/ABCDEFGHIJ","KLMNOPQR":"STUVWXYAB","CDEFGHIJ":"KLMN"},"OPQRSTUV":"WXYABCD","EFGHIJKL":"MNOP"},"QRSTUVWX":"YABCDEFG"}],"HIJKLM":null,"NOPQRSTUVWXYAB":null,"CDEFGHIJ":"KLMNOPQR"}],"STUVWXYABC":null,"DEFGHIJK":[{"LMNO":{"PQRS":"TUVW/XYAB/CDEFGH","IJKLMNOP":"QRSTUVWXY","ABCDEFGH":"IJKL"},"MNOPQRST":"UVWXYAB","CDEFGHIJ":"KLMN"}],"OPQRSTUV":1,"WXYA":"BCDEFGHI/JKLMNOPQRS","TUVWXYAB":null,"CDEFGHIJKLMNOP":null,"QRSTUVWX":"YABCDE","FGHIJKLM":"NOPQ"}]}`)

	validEncodingJSON := json.Valid(original)
	validGoJSON := gojson.Valid(original)

	if validEncodingJSON != validGoJSON {
		fmt.Printf("%v vs %v\n", validEncodingJSON, validGoJSON)

		os.Exit(1)
	}
}
```

**Comment by zimmski** [comment]
I did find another case where it fails with a segmentation fault on this PR. Will first create the issue with the invalid case, since that can be reproduced with the master (will double check that). And then move on to have a reproducer for the segmentation fault for this PR. Sorry to flipflop.

Side question: is the form of reproducers in https://github.com/goccy/go-json/pull/198#issuecomment-830175448 ok? Because that is a no-brainer to send out.

**Comment by zimmski** [comment]
Finally. I got one that i can post (as i sidenote this happens with and without https://github.com/goccy/go-json/pull/200):

```
package main

import (
	"fmt"

	//gojson "encoding/json"
	gojson "github.com/goccy/go-json"
)

func main() {
	original := []byte(`{
		"Body": {
			"List": [
				{
					"Returns": [
						{
							"Value": "10",
							"nodeType": "Literal"
						}
					],
					"nodeKind": "Return",
					"nodeType": "Statement"
				}
			],
			"nodeKind": "Block",
			"nodeType": "Statement"
		},
		"nodeType": "Function"
	}`)

	var a map[string]gojson.RawMessage
	if err := gojson.Unmarshal(original, &a); err != nil {
		panic(err)
	}
	var b map[string]gojson.RawMessage
	if err := gojson.Unmarshal(a["Body"], &b); err != nil {
		panic(err)
	}
	var c []gojson.RawMessage
	if err := gojson.Unmarshal(b["List"], &c); err != nil {
		panic(err)
	}
	var d map[string]gojson.RawMessage
	if err := gojson.Unmarshal(c[0], &d); err != nil {
		panic(err)
	}
	var e []gojson.RawMessage
	if err := gojson.Unmarshal(d["Returns"], &e); err != nil {
		panic(err)
	}
	var f map[string]gojson.RawMessage
	if err := gojson.Unmarshal(e[0], &f); err != nil {
		fmt.Printf("JSON raw: %s\n", e[0])

		panic(err)
	}
}
```

**Comment by IncSW** [comment]
@goccy @zimmski
problem can be solved by disabling slice pool

File: decode_slice.go [hunk 2]
```diff
@@ -231,8 +240,15 @@ func (d *sliceDecoder) decode(buf []byte, cursor, depth int64, p unsafe.Pointer)
 					copySlice(d.elemType, dst, src)
 				}
 				ep := unsafe.Pointer(uintptr(data) + uintptr(idx)*d.size)
-				if d.isElemPointerType {
-					*(*unsafe.Pointer)(ep) = nil // initialize elem pointer
+				if d.isElemUnmarshalJSONType {
+					receiver := unsafe_New(d.elemType)
+					if d.elemType.Kind() == reflect.Slice {
+						**(**unsafe.Pointer)(unsafe.Pointer(&ep)) = receiver
```
Comment (IncSW) [inline decode_slice.go:246]: could add here for solve
```
dst := (*sliceHeader)(ep)
dst.len = 0
dst.cap = 0
```

**Comment by goccy** [comment]
Probably, I was able to fix the problem without disabling the slice pool .

**Comment by IncSW** [comment]
In my last comment on the code i suggested solution without disabling pool, but your solution looks better, all my yesterday tests are green.

**Comment by zimmski** [comment]
Thanks @goccy and @IncSW for taking such an interested! Looking at the made changes, i am pretty sure that i would have needed lots of time to build up the context to fix them.

I tested the changes (with and without the current version of https://github.com/goccy/go-json/pull/200) and my reproducers work now as well as another set of tests in our test suite. However, there are unfortunately still problems left:

- Using the "Valid" function before unmarshaling finds some cases where go-json does not agree with encoding/json yet. I opened https://github.com/goccy/go-json/issues/199 for that.
- When i do not apply "Valid" before unmarshaling some of the JSON some of the "invalid" (encoding/json and jq agree they are valid) JSON raw data unmarshals, some not. I will try to post another reproducer for one of them.

Do you know any tooling to reduce JSON data automatically? If not, i could help out creating a reducer. Please let me know.

Since all tests passed and the code got reviewed(?), maybe this PR should be just merged and i will continue do add reproducers to new issues? What is your take on this?

**Comment by goccy** [comment]
@zimmski 
OK, so first of all, the purpose of this PR is to fix the problem of #195, so let's merge this.
Then, I will fix the `Valid` API's issue in another PR.
If you still have problems, could you create a new issue and report it ?

**Comment by zimmski** [comment]
> @zimmski
> OK, so first of all, the purpose of this PR is to fix the problem of #195, so let's merge this.

Agreed, thanks!

> If you still have problems, could you create a new issue and report it ?

I am on it. Finding send-able reproducers is a pain. Do you know of any "reducer" tooling? If not, i will create one.

**Comment by zimmski** [comment]
Btw: I think this package also found a problem in our code base.

We have a type that looks like this

```
type someStruct struct {
  ...
  someField map[string]someInterface
  ...
}
```

And the values for "someInterface" are always "null" in that case so encoding/json automatically decodes to null, however go-json does not like that. Will report that as well, because the behavior is different to encoding/json, but i found it interesting since it is practically a bug in our code.

**Comment by goccy** [comment]
Sorry, I know the tools for fuzzing, but I don't know any "reducer" tooling .
